---
kind: pipeline
type: docker
name: default

clone:
    depth: 1

steps:
    -   name: deploy
        image: automagistre/docker:stable
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker stack deploy --prune --with-registry-auth --compose-file .swarm.yml dhu
        when:
            branch: [ master ]

volumes:
    -   name: docker.sock
        host:
            path: /var/run/docker.sock
