version: '3.7'

services:
    redirect:
        image: schmunk42/nginx-redirect:0.6.0
        environment:
            SERVER_REDIRECT: github.com
            SERVER_REDIRECT_PATH: /grachevko/docker-hosts-updater
            SERVER_REDIRECT_SCHEME: https
        networks:
            - traefik
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                order: start-first
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.http.routers.whoami.rule=Host(`dhu.grachevko.ru`)"
                - "traefik.http.routers.whoami.entrypoints=websecure"
                - "traefik.http.routers.whoami.tls=true"
                - "traefik.http.routers.whoami.tls.certresolver=leresolver"
                - "traefik.http.services.whoami-service.loadbalancer.server.port=80"
                - "traefik.http.services.whoami-service.loadbalancer.server.scheme=http"

networks:
    traefik:
        external: true
        name: traefik
