version: '3.7'

services:
    dhu:
        build:
          context: .
        image: grachev/dhu
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./:/usr/local/app
            - /etc/hosts:/opt/hosts

    lb:
        image: nginx:alpine
        container_name: lb

    nginx:
        image: nginx:alpine
        labels:
            ru.grachevko.dhu: '{www,api,img,admin,profile}.nginx.local'

    nginx2:
        image: nginx:alpine
        labels:
            ru.grachevko.dhu: '{www,admin,api}.nginx.local:2'

    nginx3:
        image: nginx:alpine
        labels:
            ru.grachevko.dhu: 'img.nginx.local:3;api.nginx.local:5'

    nginx4:
        image: nginx:alpine
        labels:
            ru.grachevko.dhu: 'nginx4.local:0:lb'

    nginx5:
        image: nginx:alpine
        labels:
            ru.grachevko.dhu: 'nginx5.local:0:lb'
